### user sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Le Minh",
    "company": "Aptech",
    "address": "VN",
    "phone": "123456789",
    "email": "alo",
    "password": "alo123456"

}

### user sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    
    "email": "alo",
    "password": "alo123456"

}