### user sign up endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Le Minh",
    "company": "Aptech",
    "address": "VN",
    "phone": "123456789",
    "email": "alo",
    "password": "alo123456"

}

### user sign in endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    
    "email": "alo",
    "password": "alo123456"

}


### Get a user profile endpoint endpoint
GET  http://localhost:3001/v1/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFsbyIsImlhdCI6MTYzNjMwNjkwNSwiZXhwIjoxNjM2MzA3ODA1fQ.qTliU01kTPljLawUUrqJTvtTBcopFQsojms9xM6mQ90
#### Password reset endpoints
POST http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "alo"
}

#### Update new password endpoint
PATCH  http://localhost:3001/v1/user/reset-password
Content-Type: application/json 

{
    "email": "alo",
    "pin": 934360,
    "newPassword": "alo12"
}